version: 2

sources:
  - name: qualifier
    schema: public
    meta:
      external_location: "read_ndjson_objects('{{var('ndjson_file_path')}}')"
    tables: 
      - name: patient
      - name: observation
      - name: condition
      - name: encounter
      - name: immunization
      - name: medicationrequest
      - name: procedure