name: 'qualifier'
version: '1.5.2'
config-version: 2

profile: 'qualifier'

model-paths: ["models"]
test-paths: ["unit-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  db_json_column: "json" #json is the default for duckdb, makes docker image easier to work with
  db_is_jsonb: True
  metric_include_examples: "sample"
  # individual file locations can also be set in models/sources.yml
  # see dbt-duckdb documentation at https://github.com/jwills/dbt-duckdb
  ndjson_file_path: "../data/{name}.ndjson"
  skip_resource_count_date: False
  skip_resource_count_category: False
  skip_resource_count_category_encounter: True


seeds:
  qualifier:
    +schema: seed_data

models:
  qualifier:
    +materialized: table